#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '2'
services:
  zookeeper:
    image: zookeeper:3.6.1
    # image: registry.scontain.com:5050/sconecuratedimages/apps:zookeeper-3-alpine-scone5.9
    restart: always
    ports:
      - "2181:2181"
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    environment:
      JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/jre
      SCONE_MODE: hw
      SCONE_VERSION: 1

  bookie1:
    image: ${PRAVEGA_BK_IMAGE:-pravega/bookkeeper}
    ports:
      - "3181:3181"
    restart: always
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    environment:
      ZK_URL: zookeeper:2181
      bookiePort: 3181
      SCONE_MODE: sim
      SCONE_VERSION: 1
      SCONE_HEAP: 8G
      SCONE_PROCFS_WHITELIST: self/mounts
    links:
      - zookeeper

  bookie2:
      image: ${PRAVEGA_BK_IMAGE:-pravega/bookkeeper}
      ports:
        - "3182:3182"
      restart: always
      devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      environment:  
        ZK_URL: zookeeper:2181
        bookiePort: 3182
        SCONE_MODE: sim
        SCONE_VERSION: 1
        SCONE_HEAP: 8G
        SCONE_PROCFS_WHITELIST: self/mounts
      links:
        - zookeeper

  bookie3:
      image: ${PRAVEGA_BK_IMAGE:-pravega/bookkeeper}
      ports:
        - "3183:3183"
      restart: always
      devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3183
        SCONE_MODE: sim
        SCONE_VERSION: 1
        SCONE_HEAP: 8G
        SCONE_PROCFS_WHITELIST: self/mounts
      links:
        - zookeeper

  controller:
    image: ${PRAVEGA_IMAGE:-pravega/pravega}
    ports:
      - "9090:9090"
      - "10080:10080"
    command: controller
    restart: always
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    environment:
      SCONE_SLOTS: 384
      SCONE_VERSION: 1
      SCONE_TCS: 48
      SCONE_MODE: sim
      SCONE_HEAP: 30G
      SCONE_ESPINS: 1000000
      SCONE_SSPINS: 500
      SCONE_SSLEEP: 1
      WAIT_FOR: zookeeper:2181
      ZK_URL: zookeeper:2181
      REST_SERVER_PORT: 10080
      JAVA_OPTS: |
        -Xms512m
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/tmp/dumpfile/heap
        -XX:MaxRAMPercentage=50.0
        -XX:+UseContainerSupport
        -XX:+PrintExtendedThreadInfo
      SERVICE_HOST_IP: segmentstore
    links:
      - zookeeper
    volumes:
      - ./sgx-musl-controller.conf:/etc/sgx-musl.conf

  segmentstore:
    image: ${PRAVEGA_IMAGE:-pravega/pravega}
    ports:
      - "12345:12345"
    command: segmentstore
    restart: always
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    volumes:
      - ./data:/nfs/
      - ./sgx-musl-controller.conf:/etc/sgx-musl.conf
    environment:
      SCONE_SLOTS: 384
      SCONE_VERSION: 1
      SCONE_TCS: 48
      SCONE_MODE: sim
      SCONE_HEAP: 30G
      SCONE_ESPINS: 1000000
      SCONE_SSPINS: 500
      SCONE_SSLEEP: 1
      WAIT_FOR: bookie1:3181,bookie2:3182,bookie3:3183
      TIER2_STORAGE: "INMEMORY"
      NFS_MOUNT: /nfs
      ZK_URL: zookeeper:2181
      CONTROLLER_URL: tcp://controller:9090
      JAVA_OPTS: |
        -Xms4g
        -Xmx4g
        -XX:MaxDirectMemorySize=26g
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/tmp/dumpfile/heap
        -XX:+UseContainerSupport
        -XX:+PrintExtendedThreadInfo
    links:
      - zookeeper
      - bookie1
      - bookie2
      - bookie3
      - controller
